import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.landing}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className={styles.hero}>
        <h1 className={styles.heroTitle}>SPACESTAGRAM</h1>
        <div className={styles.showHorizon}>
          <div className={styles.horizon}>
            <svg viewBox="0 0 1512 652" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none">
              <mask id="mask0_2_16" style={{ maskType: "alpha" }} maskUnits="userSpaceOnUse" x="0" y="0" width="1512" height="652">
                <rect width="1512" height="652" fill="#C4C4C4" />
              </mask>
              <g mask="url(#mask0_2_16)">
                <path d="M-3.05176e-05 636C607 515 931 526 1512 636C2093 746 1512 253 1512 253C913.946 -1.17218 583.017 3.0647 -3.05176e-05 253C-3.05176e-05 253 -607 757 -3.05176e-05 636Z" fill="url(#paint0_radial_2_16)" />
              </g>
              <defs>
                <radialGradient id="paint0_radial_2_16" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(756 756.473) rotate(-90) scale(441.473 1742.84)">
                  <stop stopColor="#2b50c2" />
                  <stop offset="1" stopColor="#1C1F74" stopOpacity="0" />
                </radialGradient>
              </defs>
            </svg>
          </div>
        </div>
      </div>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At sed culpa quasi, minima optio adipisci maxime omnis, mollitia odit suscipit, praesentium ipsum eius. Quae dolorem mollitia dignissimos neque ex enim!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At sed culpa quasi, minima optio adipisci maxime omnis, mollitia odit suscipit, praesentium ipsum eius. Quae dolorem mollitia dignissimos neque ex enim!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At sed culpa quasi, minima optio adipisci maxime omnis, mollitia odit suscipit, praesentium ipsum eius. Quae dolorem mollitia dignissimos neque ex enim!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At sed culpa quasi, minima optio adipisci maxime omnis, mollitia odit suscipit, praesentium ipsum eius. Quae dolorem mollitia dignissimos neque ex enim!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At sed culpa quasi, minima optio adipisci maxime omnis, mollitia odit suscipit, praesentium ipsum eius. Quae dolorem mollitia dignissimos neque ex enim!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At sed culpa quasi, minima optio adipisci maxime omnis, mollitia odit suscipit, praesentium ipsum eius. Quae dolorem mollitia dignissimos neque ex enim!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At sed culpa quasi, minima optio adipisci maxime omnis, mollitia odit suscipit, praesentium ipsum eius. Quae dolorem mollitia dignissimos neque ex enim!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At sed culpa quasi, minima optio adipisci maxime omnis, mollitia odit suscipit, praesentium ipsum eius. Quae dolorem mollitia dignissimos neque ex enim!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At sed culpa quasi, minima optio adipisci maxime omnis, mollitia odit suscipit, praesentium ipsum eius. Quae dolorem mollitia dignissimos neque ex enim!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At sed culpa quasi, minima optio adipisci maxime omnis, mollitia odit suscipit, praesentium ipsum eius. Quae dolorem mollitia dignissimos neque ex enim!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At sed culpa quasi, minima optio adipisci maxime omnis, mollitia odit suscipit, praesentium ipsum eius. Quae dolorem mollitia dignissimos neque ex enim!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At sed culpa quasi, minima optio adipisci maxime omnis, mollitia odit suscipit, praesentium ipsum eius. Quae dolorem mollitia dignissimos neque ex enim!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At sed culpa quasi, minima optio adipisci maxime omnis, mollitia odit suscipit, praesentium ipsum eius. Quae dolorem mollitia dignissimos neque ex enim!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At sed culpa quasi, minima optio adipisci maxime omnis, mollitia odit suscipit, praesentium ipsum eius. Quae dolorem mollitia dignissimos neque ex enim!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At sed culpa quasi, minima optio adipisci maxime omnis, mollitia odit suscipit, praesentium ipsum eius. Quae dolorem mollitia dignissimos neque ex enim!</p>
    </div>
  )
}
